### ISSUE TITLE
Change input of bam2fastq

### ISSUE THREAD

**Issue by mAGLAVE** [gustaveroussy/bigr_long-reads_bulk#38]
Actually input bam are aligned bam but we should use unaligned bam.

**Comment by sandratra-rab** [comment]
1) add a step to concatenate ubam file
2) add a step to sort and index ubam file
3) add ubam file as input to bam2fq_qc.smk (rule samtools_bam_to_fastq)

**Comment by sandratra-rab** [comment]
Ready for release 2.1.0
