### ISSUE TITLE
change name file WM100_SNV_indel.vcf.gz

### ISSUE THREAD

**Issue by tomgutman** [gustaveroussy/bigr_long-reads_bulk#9]
It seems that the file named "XXX_SNV_indel.vcf.gz" contains only SNVs.

It would be nice to change the name of this file to XXX_SNV.vcf.gz and change the file "indel.vcf.gz" to XXX_indel.vcf.gz" to avoid any confusion

To go even further :
in the "SNV_calling" folder, it would be nice to have a "germline" and an "somatic" folder containing all the files such as

XXX_SNV.vcf.gz ; XXX_SNV_PASS.vcf.gz ; XXX_SNV.ann.vcf.gz etc...

**Comment by sandratra-rab** [comment]
Thanks Tom !

Added in the next release:
`_snv.vcf.gz` and `_indel.vcf.gz` suffixes for ClairS output
`Germline/` and `Somatic/` output directories depending on the variant calling mode which was used by the pipeline
